### ISSUE TITLE
Hours not saving if inputted via multiple tabbing to next input field

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#589]
I got to another persons My StaffPlan view, change hours on a project (via inputting hours then tab input hours tab...) and click People. Those hours I just edited are not saved (that persons totals on People is not updated, and if I return to that persons My StaffPlan view, those hours are reset to their prior state, losing my changes).

If you recreate try doing it by edit hours > tab > edit hours > tab... do this a few times.
And make your edit hours a `0`.
It seems that it may be saving the first edit, but not subsequent edits, and it doesn't seem to like `0`.

See video for flow...
https://github.com/user-attachments/assets/7cf824ca-fee4-44cc-8da9-9953299ae461

Related issue,
If there are existing hours, and I edit to `0` and hit enter, it will not save that `0`.

**Comment by zhukovdigital** [comment]
@ericbenwa The behavior as in the video is not reproducible for me. It may have been fixed in previous PRs. Can you check again if this behavior is reproduced now?

@ericbenwa @fermion I also noticed that if you enter a value greater than 168, the backend does not save the changes, but visually they happen and after refreshing the page the values become as they were.
It is logical not to save values more than hours in a week (7 * 24 = 168), but we need to show it visually to the user.

**Comment by fermion** [comment]
@zhukovdigital @ericbenwa it's [a validation on the backend](https://github.com/goinvo/staffplan_redux/blob/abda973ca82042e85c2507da3e2f9d6f1ebc6e09/app/models/work_week.rb#L12-L13), work weeks can't have more than 168 hours added. There are 168 hours in any week (24 * 7).

**Comment by ericbenwa** [comment]
@zhukovdigital Just tested this again. I can still reproduce the hours not saving issue (video attached that I just took).

Start with a row of '5' hours.
Then change them all to '0' by tabbing to each input field.
Do at least five input fields set to '0'.
Then navigate to another page and back.
= Not all input fields saved those changes.

Then repeat these steps after two or three times it then seems to correctly save the changes.
https://github.com/user-attachments/assets/6b5d8dfe-ccfb-4f83-98a3-e2ee7acb0635

**Comment by zhukovdigital** [comment]
@ericbenwa This problem relates to #465 . And it is most likely related to the way the backend handles value 0 and empty string.

And about entering more than 168 hours, what should we do? Any ideas how to inform the user that more than 168 hours cannot be entered?

**Comment by ericbenwa** [comment]
@zhukovdigital 
`And about entering more than 168 hours, what should we do?`
I'll put that on my list to think about – thank you for finding!

**Comment by fermion** [comment]
@zhukovdigital looking at this now, I'm not sure this is related to the backend handling of 0 or '' values, since the save does seem to work the second time (from @ericbenwa's video). I'm going to see if I can repro locally to better understand this.

**Comment by fermion** [comment]
@zhukovdigital from what I can see this looks like another issue with client side state not updating itself correctly as values are being mutated. See this screen cap:

https://github.com/user-attachments/assets/633028f2-9ef1-4560-9eb2-a494245c7651

I followed the same steps that @ericbenwa did in his video, only at the end I refresh the project page. When I do you can see that the page is rendering the weeks where I've tried to blank out the values correctly. Let me know if I can help here!

**Comment by zhukovdigital** [comment]
There's a problem on the backend. But just in case I added validation at the front. Now input take only numbers in range 0 -168

**Comment by zhukovdigital** [comment]
@ericbenwa  There's a problem on the backend. When we send 0 or nothing in estHours - response from backend prev data.
When we send 0 or nothing in actHours - response from backend new data.

But just in case I added validation at the front. Now input take only numbers in range 0 -168 or nothing

**Comment by zhukovdigital** [comment]
@fermion @ericbenwa 
Here i show, that backend response. 
Added validation in front.
You could test in PR
https://github.com/goinvo/staffplan-next-app/pull/693

https://github.com/user-attachments/assets/d8611e68-e36b-4aac-bbd4-bf5e5828715e

**Comment by fermion** [comment]
@zhukovdigital can you try calling the `upsertWorkWeeks` mutation here? That takes an array of object data for a work week and _should_ do the correct thing. I'd actually like to deprecate / remove `upsertWorkWeek` in addition to `upsertProject` in favor of `upsertProjectWithInput`.

**Comment by zhukovdigital** [comment]
const [upsertWorkWeeks] = useMutation(UPSERT_WORKWEEKS, {...
here mutation upsertWorkWeeks now.
But when we enter 0 - than back response data with prev estimatedHours. 
When we enter another number - back response data with new estimatedHours.

And when input empty, we enter 0 - back response data: null 
Is this how it should be?

**Comment by HankC138** [comment]
@ericbenwa is this still occurring for you? Following the steps I'm not having the same problem? Tabbing and editing into 0's seems to effectively save for me

**Comment by ericbenwa** [comment]
Still happening for me if i enter 0 tab 0 tab OR delete (so nil) tab delete (so nil).
