### ISSUE TITLE
Overall snappiness upon clicking actionable items may take seconds to do the action.

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/staffplan-next-app#813]
it’s not limited to this example… 
but here’s an example where clicking “Plan” takes 3 seconds to switch to “Proposed”
and on this example I then clicked Proposed and it did a strange switch to Plan and back to Proposed again.

https://github.com/user-attachments/assets/3683a869-004a-4ee5-bc39-6690a52447d3

**Comment by HankC138** [comment]
@ericbenwa in terms of this particular case regarding status. I believe I've fixed it. On my local instance the flicker is stopped and the switch is snappier. Let me know if the results are the same for you on production.

**Comment by ericbenwa** [comment]
@HankC138 

I'm still seeing the lagginess.
Watch till the end. It lags on each switch... and by the end the bar charts do a double color switch on a single press... it's showing "Plan" as the text title, and the bar charts have the Plan color (correct) but then quickly switches on its own again to the Proposed color (incorrect).

https://github.com/user-attachments/assets/ec0c4dad-260f-427b-a576-1e4d31aca7c5
